config/routes.rb
Rails.application.routes.draw do
  
  root  'landscaping#home'
  get 'about', to: 'landscaping#about'

  resources :customers
  # For details on the DSL availale within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
	validates :customer_first_nm, presence: true, length: {minimum:3, maximum:25}
	validates :customer_last_nm, presence: true, length: {minimum:3, maximum:25}
	validates :customer_email, presence: true, length: {minimum:10, maximum:30}
end	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

	def new
       @customer = Customer.new
	end	

	def show
       @customer = Customer.find(params[:id])
	end	

	def index
		@customers = Customer.all

       
	end	

	def create
		@customer = Customer.new(customer_params)

		if @customer.save
			flash[:notice] = "Customer was Successfully Created"
            redirect_to customer_path(@customer)
        else
           render 'new'
        end       
	end	

	def customer_params
       params.require(:customer).permit(:customer_first_nm,:customer_last_nm,:customer_email,:comment)
	end	

	def edit
      @customer = Customer.find(params[:id])
	end	
	def destroy
		@customer = Customer.find(params[:id])
		@customer.destroy
		flash[:notice] = "customer was deleted succesfully"
		redirect_to customers_path

	end	

	def update
       @customer = Customer.find(params[:id])

		if @customer.update(customer_params)
			flash[:notice] = "Customer was Successfully Updated"
            redirect_to customer_path(@customer)
        else
           render 'edit'
        end 
	end	

end	

app/controllers/landscaping_controller.rb
class LandscapingController < ApplicationController

	def home
		
	end
	
	def about
	end	

	

end	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/edit.html.erb
<h1>  Create new customers </h1>
  <% if @customer.errors.any? %>
     <h2>Cutomer could not be updated </h2>
     <ul>
     <% @customer.errors.full_messages.each do |msg| %>
         
         	<li> <%= msg %> </li>

         
     <%end%>
 </ul>
   <%end%>  

   <%= form_for @customer do |t| %>
      <p>
      	<%= t.label :customer_first_nm %> <br/>
      	<%= t.text_field :customer_first_nm %>
      </p>
      <p>
      	<%= t.label :customer_last_nm %> <br/>
      	<%= t.text_field :customer_last_nm %>
      </p>
      <p>
      	<%= t.label :customer_email %> <br/>
      	<%= t.text_field :customer_email %>
      </p>
      <p>
      	<%= t.label :comment %> <br/>
      	<%= t.text_area :comment %>
      </p>
    <p>  <%= t.submit "Update"%></p>
   
   <%end%> 

app/views/customers/index.html.erb
<div> <h1> List of Customer</h1></div>


<table>
	<tr> 
		<th>
			First Name
		</th>
		<th>
			Last Name
		</th>
		<th>
			Email
		</th>
		<th>
			Comment
		</th>
	
    </tr>
	
		<% @customers.each do |customer| %>
		<tr>
		<td> <%= customer.customer_first_nm %> </td>
		<td> <%= customer.customer_last_nm %> </td>
		<td> <%= customer.customer_email %> </td>
		<td> <%= customer.comment %> </td>
		<td> <%= link_to "Show", customer_path(customer) %> </td>
		<td> <%= link_to "Edit", edit_customer_path(customer) %> </td>
		<td> <%= link_to "Delete", customer_path(customer), method: :delete,data:{confirm:"Are you sure"} %> </td>
	</tr>
		<%end%>
	
</table>

<%= link_to "Create Customer", new_customer_path() %> |
<%= link_to "Home Page", root_path() %> 

app/views/customers/new.html.erb
<h1>  Create new customers </h1>
  <% if @customer.errors.any? %>
     <h2>Cutomer could not be inserted </h2>
     <ul>
     <% @customer.errors.full_messages.each do |msg| %>
         
         	<li> <%= msg %> </li>

         
     <%end%>
 </ul>
   <%end%>  

   <%= form_for @customer do |t| %>
      <p>
      	<%= t.label :customer_first_nm %> <br/>
      	<%= t.text_field :customer_first_nm %>
      </p>
      <p>
      	<%= t.label :customer_last_nm %> <br/>
      	<%= t.text_field :customer_last_nm %>
      </p>
      <p>
      	<%= t.label :customer_email %> <br/>
      	<%= t.text_field :customer_email %>
      </p>
      <p>
      	<%= t.label :comment %> <br/>
      	<%= t.text_area :comment %>
      </p>
    <p>  <%= t.submit "Submit"%></p>

    <%= link_to "Home", root_path %>
   
   <%end%> 

app/views/customers/show.html.erb
<h1>  showing this customers</h1>

<p>  First Name: <%=  @customer.customer_first_nm %> </p>
<p>  Last Name: <%= @customer.customer_last_nm %> </p>
<p>  Email: <%= @customer.customer_email %> </p>
<p> Comment <%= @customer.comment %> </p>

<%= link_to "Edit Article", edit_customer_path(@customer) %> | 

<%=link_to "List all article", customers_path() %>

app/views/landscaping/about.html.erb
<div> <h1> About Landscaping </h1></div>

<%= link_to "Home", root_path %>

app/views/landscaping/home.html.erb
<div class="jumbotron">
  <h1>Green, world!</h1>
  <p>...</p>
  <p><a class="btn btn-primary btn-lg button" href="#" role="button">Call Us</a></p>
</div>

<section class="w3-container w3-center w3-content" style="max-width:600px">
  <h2 class="w3-wide">DFW LANDSCAPING</h2>
  <p class="w3-opacity"><i>Let's Go Green</i></p>
  <p class="w3-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
</section>


<!-- Band Members -->
<section class="w3-row-padding w3-center w3-light-grey">
  <article class="w3-third">
    <p>DFW</p>
    <%= link_to image_tag("img2.jpg",width:"90%" , alt: "Laurie attitude") %>
    <p>LANDSCAPING</p>
  </article>
  <article class="w3-third">
    <p>DFW</p>
    <%= link_to image_tag("img2.jpg",width:"90%" , alt: "Laurie attitude") %>
    <p>LANDSCAPING</p>
  </article>
  <article class="w3-third">
    <p>DFW</p>
    <%= link_to image_tag("img2.jpg",width:"90%" , alt: "Laurie attitude") %>
    <p>LANDSCAPING</p>
  </article>
</section>

<section class="w3-container w3-content" style="max-width:600px">
  <h2 class="w3-wide"> Photo Gallary Of Our Work</h2>
</section>


  <div class="w3-content">
  	<div id="my-slider" class="carousel slide" data-ride="carousel">
  		
  		<!-- indicators dot nav -->

  		<ol class="carousel-indicators">
  			<li data-target="#my-slider" data-slide-to="0" class="active">
  				
  			</li>
  			<li data-target="#my-slider" data-slide-to="1">
  				
  			</li>
  		</ol>

  		<!-- wrapper for slides -->

  		<div class="carousel-inner" role="listbox">
  			<div class="item active">
  				<%= link_to image_tag("img3.jpg",width:"100%" ,alt: "Laurie attitude") %>
  				<div class="carousel-caption">
  					<h1> first pic</h1>
  				</div>
  			</div>
  			<div class="item">
  				<%= link_to image_tag("img3.jpg",width:"100%" , alt: "Laurie attitude") %>
  				<div class="carousel-caption">
  					<h1> second pic</h1>
  				</div>
  			</div>
  			<div class="item">
  				<%= link_to image_tag("img3.jpg",width:"100%" , alt: "Laurie attitude") %>
  				<div class="carousel-caption">
  					<h1> third pic</h1>
  				</div>
  			</div>
  		</div>
  		
     


  		<!-- controls or next and prev buttons -->
  		<a class="carousel-control-prev" href="#my-slider" data-slide="prev">
		    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
		    
		  </a>
		  <a class="carousel-control-next" href="#my-slider" data-slide="next">
		     <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
		     
		  </a>
  	</div>
    
  </div>
  
</div>

<!-- Footer -->
<footer class="w3-container w3-padding-64 w3-center w3-black w3-xlarge">
  <a href="#"><i class="fa fa-facebook-official"></i></a>
  <a href="#"><i class="fa fa-pinterest-p"></i></a>
  <a href="#"><i class="fa fa-twitter"></i></a>
  <a href="#"><i class="fa fa-flickr"></i></a>
  <a href="#"><i class="fa fa-linkedin"></i></a>
  <p class="w3-medium">
  Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">Rails <%= link_to "About Us", about_path %> |<%= link_to "Create Customer", new_customer_path() %> |</a>
  </p>
 
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" id='logo' href="">DFW</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" >
      <ul class="nav navbar-nav">
        <li><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" id ='float_letter'>
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LandscapeWebsite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     
  </head>

  <body>
    <% flash.each do |name,msg| %>
    <ul>
      <li> <%= msg %> </li>
    </ul>
    <% end %>
    <%= render 'layouts/navigation' %>
     <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>